/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) CPNTgen_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[59] = {1, 28, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* cpnt:(t)->(p0) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=9.8999999999999999e-01;
  a1=arg[0]? arg[0][0] : 0;
  a0=pow(a0,a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

/* map28_cpnt:(t[1x28])->(p0[1x28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real* *res1;
  const casadi_real* *arg1;
  arg1 = arg+1;
  for (i=0; i<1; ++i) arg1[i]=arg[i];
  res1 = res+1;
  for (i=0; i<1; ++i) res1[i]=res[i];
  for (i=0; i<28; ++i) {
    if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
    if (arg1[0]) arg1[0]+=1;
    if (res1[0]) res1[0]+=1;
  }
  return 0;
}

CASADI_SYMBOL_EXPORT int map28_cpnt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int map28_cpnt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int map28_cpnt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void map28_cpnt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int map28_cpnt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void map28_cpnt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void map28_cpnt_incref(void) {
}

CASADI_SYMBOL_EXPORT void map28_cpnt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int map28_cpnt_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int map28_cpnt_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real map28_cpnt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* map28_cpnt_name_in(casadi_int i){
  switch (i) {
    case 0: return "t";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* map28_cpnt_name_out(casadi_int i){
  switch (i) {
    case 0: return "p0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* map28_cpnt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* map28_cpnt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int map28_cpnt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
