/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cas_obj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};

static const casadi_real casadi_c0[30] = {1., 1., 1., 9.0000000000000002e-01, 9.0000000000000002e-01, 9.0000000000000002e-01, 8.1000000000000005e-01, 8.1000000000000005e-01, 8.1000000000000005e-01, 7.2900000000000009e-01, 7.2900000000000009e-01, 7.2900000000000009e-01, 6.5610000000000002e-01, 6.5610000000000002e-01, 6.5610000000000002e-01, 5.9049000000000007e-01, 5.9049000000000007e-01, 5.9049000000000007e-01, 5.3144100000000005e-01, 5.3144100000000005e-01, 5.3144100000000005e-01, 4.7829690000000008e-01, 4.7829690000000008e-01, 4.7829690000000008e-01, 4.3046721000000010e-01, 4.3046721000000010e-01, 4.3046721000000010e-01, 3.8742048900000009e-01, 3.8742048900000009e-01, 3.8742048900000009e-01};

/* cas_obj:(con[30],knx[30],lab[30])->(obj) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, *w1=w+30, w2, *w3=w+61, w4, *w5=w+92, w6, *w7=w+96, w8, *w9=w+100;
  /* #0: @0 = [1, 1, 1, 0.9, 0.9, 0.9, 0.81, 0.81, 0.81, 0.729, 0.729, 0.729, 0.6561, 0.6561, 0.6561, 0.59049, 0.59049, 0.59049, 0.531441, 0.531441, 0.531441, 0.478297, 0.478297, 0.478297, 0.430467, 0.430467, 0.430467, 0.38742, 0.38742, 0.38742] */
  casadi_copy(casadi_c0, 30, w0);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 30, w1);
  /* #2: @1 = (1./@1) */
  for (i=0, rr=w1, cs=w1; i<30; ++i) *rr++ = (1./ *cs++ );
  /* #3: @2 = -1 */
  w2 = -1.;
  /* #4: @1 = (@1/@2) */
  for (i=0, rr=w1; i<30; ++i) (*rr++) /= w2;
  /* #5: @2 = 1.84079 */
  w2 = 1.8407947777401397e+00;
  /* #6: @3 = input[2][0] */
  casadi_copy(arg[2], 30, w3);
  /* #7: @4 = 3 */
  w4 = 3.;
  /* #8: @3 = pow(@3,@4) */
  for (i=0, rr=w3, cr=w3; i<30; ++i) (*rr++)  = pow((*cr++),w4);
  /* #9: @3 = (@2*@3) */
  for (i=0, rr=w3, cs=w3; i<30; ++i) (*rr++)  = (w2*(*cs++));
  /* #10: @2 = 3 */
  w2 = 3.;
  /* #11: @3 = (@3/@2) */
  for (i=0, rr=w3; i<30; ++i) (*rr++) /= w2;
  /* #12: @1 = (@1-@3) */
  for (i=0, rr=w1, cs=w3; i<30; ++i) (*rr++) -= (*cs++);
  /* #13: @2 = dot(@0, @1) */
  w2 = casadi_dot(30, w0, w1);
  /* #14: @4 = 0.348678 */
  w4 = 3.4867844010000010e-01;
  /* #15: @5 = ones(3x1) */
  casadi_fill(w5, 3, 1.);
  /* #16: @6 = 0.309343 */
  w6 = 3.0934343434343442e-01;
  /* #17: @0 = input[1][0] */
  casadi_copy(arg[1], 30, w0);
  /* #18: @7 = @0[27:30] */
  for (rr=w7, ss=w0+27; ss!=w0+30; ss+=1) *rr++ = *ss;
  /* #19: @8 = 0.33 */
  w8 = 3.3000000000000002e-01;
  /* #20: @7 = pow(@7,@8) */
  for (i=0, rr=w7, cr=w7; i<3; ++i) (*rr++)  = pow((*cr++),w8);
  /* #21: @7 = (@6*@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #22: @7 = (1./@7) */
  for (i=0, rr=w7, cs=w7; i<3; ++i) *rr++ = (1./ *cs++ );
  /* #23: @6 = -1 */
  w6 = -1.;
  /* #24: @7 = (@7/@6) */
  for (i=0, rr=w7; i<3; ++i) (*rr++) /= w6;
  /* #25: @9 = all_0.613598(3x1) */
  casadi_fill(w9, 3, 6.1359825924671318e-01);
  /* #26: @7 = (@7-@9) */
  for (i=0, rr=w7, cs=w9; i<3; ++i) (*rr++) -= (*cs++);
  /* #27: @6 = dot(@5, @7) */
  w6 = casadi_dot(3, w5, w7);
  /* #28: @8 = 0.1 */
  w8 = 9.9999999999999978e-02;
  /* #29: @6 = (@6/@8) */
  w6 /= w8;
  /* #30: @4 = (@4*@6) */
  w4 *= w6;
  /* #31: @2 = (@2+@4) */
  w2 += w4;
  /* #32: @4 = 12017.5 */
  w4 = 1.2017480000000000e+04;
  /* #33: @2 = (@2/@4) */
  w2 /= w4;
  /* #34: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int cas_obj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cas_obj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cas_obj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cas_obj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cas_obj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cas_obj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cas_obj_incref(void) {
}

CASADI_SYMBOL_EXPORT void cas_obj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cas_obj_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int cas_obj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cas_obj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cas_obj_name_in(casadi_int i){
  switch (i) {
    case 0: return "con";
    case 1: return "knx";
    case 2: return "lab";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cas_obj_name_out(casadi_int i){
  switch (i) {
    case 0: return "obj";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cas_obj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cas_obj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cas_obj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 103;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
